import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin_uniqueA@example.com',
      password: bcrypt.hashSync('55555'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user_doe@example.com',
      password: bcrypt.hashSync('123'),
      isAdmin: false,
    },
    {
      name: 'Janny',
      email: 'user_jen@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
    {
      name: 'Manny',
      email: 'user_manny@example.com',
      password: bcrypt.hashSync('1235'),
      isAdmin: false,
    },
    {
      name: 'Barny',
      email: 'user_ban@example.com',
      password: bcrypt.hashSync('1236'),
      isAdmin: false,
    },
    {
      name: 'Mikky',
      email: 'user_mik@example.com',
      password: bcrypt.hashSync('1237'),
      isAdmin: false,
    },
    {
      name: 'Polly',
      email: 'user_pol@example.com',
      password: bcrypt.hashSync('1238'),
      isAdmin: false,
    },
    {
      name: 'Billy',
      email: 'user_bil@example.com',
      password: bcrypt.hashSync('1239'),
      isAdmin: false,
    },
    {
      name: 'Milly',
      email: 'user_mil@example.com',
      password: bcrypt.hashSync('1231'),
      isAdmin: false,
    },
    {
      name: 'Molly',
      email: 'user_mol@example.com',
      password: bcrypt.hashSync('12312'),
      isAdmin: false,
    },
    {
      name: 'Coll',
      email: 'user_col@example.com',
      password: bcrypt.hashSync('12314'),
      isAdmin: false,
    },
    {
      name: 'Fanny',
      email: 'user_fan@example.com',
      password: bcrypt.hashSync('12315'),
      isAdmin: false,
    },
    {
      name: 'Danny',
      email: 'user_dan@example.com',
      password: bcrypt.hashSync('12316'),
      isAdmin: false,
    },


  ],
  products: [
    {
      name: "10000 BTU Window AC",
      slug: "btu-dual-inverter-air-conditioner",
      category: "Window Air Conditioner",
      image: "/images/p1.jpg",
      price: 449,
      discount: 30,
      countInStock: 10,
      brand: "LG",
      rating: 4.5,
      numReviews: 5,
      description: "10000 BTU, Estimated Cooling Area 450 sq. ft. Automatically restarts minutes after power is restored when a power failure occurs. LoDecibel™ Quiet Operation, LG ThinQ® Technology. The Clean Filter Alert lets you know when it’s time to clean. Simply remove the filter to wash. Make temperature adjustments and fan speed selection on the easy to use control panel or remote. This Dual Inverter ENERGY STAR® unit meets the EPA's standards for energy efficiency and savings.",
      features: "Energy Saving",
      btu: 10000,
      areaCoverage: 16,
      energyEfficiency: 9,
      documents: [
        {
          url: "https://www.lg.com/us/support/products/documents/LWHD6500.pdf",
          type: "PDF",
          description: "User Manual for LG 10000 BTU Window AC",
        },
        {
          url: "https://www.lg.com/us/support/products/documents/LW1016ER%20Spec%20Sheet.pdf",
          type: "PDF",
          description: "Technical Specifications for LG 10000 BTU Window AC",
        },
        {
          url: "https://gscs.lge.com/gscs/support/fileupload/downloadFile.do?fileId=WK0K7TKOXp639VkW44X2Q&portalId=P1",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "8000 BTU Window AC",
      slug: "btu-window-air-conditioner",
      category: "Window Air Conditioner",
      image: "/images/p2.jpg",
      price: 279,
      discount: 50,
      countInStock: 8,
      brand: "LG",
      rating: 3.5,
      numReviews: 4,
      description: "8000 BTU, Estimated Cooling Area 350 Sq. Ft, 115 Volt, Window Installation Kit, Slide Out Washable Filter & Filter Alert, 2 Fan Speed Cooling, Energy Saver Function.",
      features: "Remote Control",
      btu: 8000,
      areaCoverage: 13,
      energyEfficiency: 8,
      documents: [
        {
          url: "https://www.lg.com/us/support/products/documents/LWHD6500.pdf",
          type: "PDF",
          description: "User Manual for LG 8000 BTU Window AC",
        },
        {
          url: "https://www.lg.com/us/support/products/documents/LW8016ER%20Spec%20Sheet.pdf",
          type: "PDF",
          description: "Technical Specifications for LG 8000 BTU Window AC",
        },
        {
          url: "https://gscs.lge.com/gscs/support/fileupload/downloadFile.do?fileId=WK0K7TKOXp639VkW44X2Q&portalId=P1",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],

    },
    {
      name: "12000 BTU Window AC",
      slug: "btu-dual-inverter-smart-air-conditioner",
      category: "Window Air Conditioner",
      image: "/images/p3.jpg",
      price: 529,
      discount: 20,
      countInStock: 12,
      brand: "LG",
      rating: 0,
      numReviews: 1,
      description: "12000 BTU, Estimated Cooling Area 550 sq. ft., 115 Volt, ENERGY STAR Certified, Window Installation Kit, Slide-Out Washable Filter & Filter Alert, 3 Fan Speed Cooling.",
      features: "Wi-Fi",
      btu: 12000,
      areaCoverage: 20,
      energyEfficiency: 10,
      documents: [
        {
          url: "https://www.lg.com/us/support/products/documents/LWHD6500.pdf",
          type: "PDF",
          description: "User Manual for LG 12000 BTU Window AC",
        },
        {
          url: "https://www.lg.com/us/support/products/documents/LW1216ER%20Spec%20Sheet.pdf",
          type: "PDF",
          description: "Technical Specifications for LG 12000 BTU Window AC",
        },
        {
          url: "https://gscs.lge.com/gscs/support/fileupload/downloadFile.do?fileId=WK0K7TKOXp639VkW44X2Q&portalId=P1",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],

    },
    {
      name: "6000 BTU Portable AC",
      slug: "btu-portable-air-conditioner",
      category: "Portable Air Conditioner",
      image: "/images/p4.jpg",
      price: 329,
      discount: 30,
      countInStock: 2,
      brand: "LG",
      rating: 2.5,
      numReviews: 3,
      description: "6000 BTU (US DOE)/ 10,000 BTU (ASHRAE)*, 3-in-1 Operation (Cool/Dehumidify/Fan), Auto Swing Air Vent, Installation Kit Included, Estimated Cooling Area 250 Sq. Ft.",
      features: "Remote Control",
      btu: 6000,
      areaCoverage: 10,
      energyEfficiency: 8,
      documents: [
        {
          url: "https://dzrf1tezfwb3j.cloudfront.net/uploads/ADocuments/90281/2020-03-04-16-43-52.pdf",
          type: "PDF",
          description: "User Manual for LG 6000 BTU Portable AC",
        },
        {
          url: "https://www.lg.com/us/support/products/documents/LP0621WSR%20Spec%20Sheet.pdf",
          type: "PDF",
          description: "Technical Specifications for LG 6000 BTU Portable AC",
        },
        {
          url: "https://gscs.lge.com/gscs/support/fileupload/downloadFile.do?fileId=WK0K7TKOXp639VkW44X2Q&portalId=P1",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "18000 BTU Mini Split AC",
      slug: "18000-btu-Mini-Split-air-conditioner",
      category: "Mini Split AC",
      image: "/images/p5.jpg",
      price: 899.99,
      discount: 0,
      countInStock: 4,
      brand: "Senville",
      rating: 4.5,
      numReviews: 139,
      description: "18000 BTU Mini Split Air Conditioner and Heat Pump System, LETO Series by Senville offers you an efficient way to heat and cool any room. 19 SEER (HE) High Efficiency Air Conditioner & Heater. With Built-In Heat Pump (Up to -15C / 5F) Suitable for Most Climates. DC Inverter Technology for Minimal Energy Consumption (Up to 48% Savings per Year). Built-In De-humidification Function, Fan and Turbo Function for Complete Climate Control. Recommended for rooms sized 700-1000 sq. ft. Requires professional installation.",
      features: "Remote Control",
      btu: 18000,
      areaCoverage: 100,
      energyEfficiency: 12,
      documents: [
        {
          url: "https://senville.com/content/manuals/downloads/leto-series-installation-manual.pdf",
          type: "PDF",
          description: "User Manual for Senville 18000 BTU Mini Split AC",
        },
        {
          url: "https://senville.com/18000-btu-mini-split-air-conditioner-sena-18hf/",
          type: "PDF",
          description: "https://senville.com/content/manuals/senville-catalog.pdf",
        },
        {
          url: "https://manuals.plus/wp-content/uploads/2023/08/Senville-18000-BTU-Floor-Mounted-Mini-Split-Heat-Pump-Instruction-Manual_2.png",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "24000 BTU Mini Split AC",
      slug: "24000-btu-Mini-Split-air-conditioner",
      category: "Mini Split AC",
      image: "/images/p6.jpg",
      price: 872.19,
      discount: 20,
      countInStock: 4,
      brand: "Towallmark",
      rating: 3.5,
      numReviews: 39,
      description: "24000 Efficient Mini Split AC Cooling & Heating System: With 24,000 BTUs and a 23 SEER2 rating, 208/230V, our split air conditioner provides cooling and heating capabilities, ensuring optimal temperature control in any season. This pre-charged air conditioner unit features a ductless mini split inverter plus system with a heat pump and DC Inverter technology providing up to 30% power savings.",
      features: "Remote Control",
      btu: 24000,
      areaCoverage: 139,
      energyEfficiency: 13,
      documents: [
        {
          url: "https://www.tcl.com/content/dam/brandsite/region/australia/AU_Mediacenter/download/Multi-Split-User-Manual.pdf",
          type: "PDF",
          description: "User Manual for Towallmark 24000 BTU  Mini Split AC",
        },
        {
          url: "https://www.tcl.com/content/dam/brandsite/region/australia/AU_Mediacenter/download/Multi-Split-User-Manual.pdf",
          type: "PDF",
          description: "Technical Specifications for Towallmark 24000 BTU  Mini Split AC",
        },
        {
          url: "https://manuals.plus/wp-content/uploads/2023/08/Senville-18000-BTU-Floor-Mounted-Mini-Split-Heat-Pump-Instruction-Manual_2.png",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "30000 BTU Mini Split AC",
      slug: "30000-btu-Mini-Split-air-conditioner",
      category: "Mini Split AC",
      image: "/images/p7.jpg",
      price: 6914,
      discount: 0,
      countInStock: 1,
      brand: "Daikin",
      rating: 3,
      numReviews: 30,
      description: "Daikin 30000 Btu 20.2 Seer 4-Zone Mini Split Heat Pump System - 7K-7K-7K-9K - 5MXS48TVJU - (3) CTXS07LVJU - FTXS09LVJU",
      features: "Remote Control",
      btu: 30000,
      areaCoverage: 180,
      energyEfficiency: 14,
      documents: [
        {
          url: "https://www.daikinac.com/content/assets/DOC/OperationManuals/FTXS15_18_24LVJU%20Operation%20Manual.pdf",
          type: "PDF",
          description: "User Manual for Daikin 30000 BTU  Mini Split AC",
        },
        {
          url: "https://www.daikinac.com/content/assets/Uploads/PM-DCRG.pdf",
          type: "PDF",
          description: "Technical Specifications for Daikin 30000 BTU  Mini Split AC",
        },
        {
          url: "https://manuals.plus/wp-content/uploads/2023/08/Senville-18000-BTU-Floor-Mounted-Mini-Split-Heat-Pump-Instruction-Manual_2.png",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "16000 BTU Wind-Free TM AC",
      slug: "16000-btu-Wind-Free-air-conditioner",
      category: "Wind-Free TM Cooling",
      image: "/images/p8.jpg",
      price: 812.99,
      discount: 10,
      countInStock: 2,
      brand: "Samsung",
      rating: 2,
      numReviews: 20,
      description: " This 16000 BTU  Mini Split AC Wind-Free TM Cooling 5460-22860 BTU. Heating 4435-27300 BTU. Sound Levels insite 58 db outside 65 db. Inverter, Wi-Fi, Wind-Free™ Cooling, AI Comfort, Motion Sensor",
      features: "Smart Things",
      btu: 16000,
      areaCoverage: 225,
      energyEfficiency: 15.45,
      documents: [
        {
          url: "https://refripartes.com/uploads/User%20Manual%20-%20Excellence%20Wind%20Free.pdf",
          type: "PDF",
          description: "User Manual for Samsung 16000 BTU  Mini Split AC",
        },
        {
          url: "https://images.samsung.com/is/content/samsung/assets/ph/home-appliances/ebrochures/Room_and_System_Air_Conditioner_Digital_Brochure.pdf",
          type: "PDF",
          description: "Technical Specifications for Samsung 16000 BTU  Mini Split AC",
        },
        {
          url: "https://blog.costway.com/zb_users/upload/2024/07/202407221721717298238921.png",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    },
    {
      name: "39000 Btu Mini Split Heat Pump System",
      slug: "39000-btu-Mini-Split-heat-pump-system",
      category: "Mini Split Heat Pump System",
      image: "/images/p9.jpg",
      price: 6650.00,
      discount: 0,
      countInStock: 6,
      brand: "Mitsubishi",
      rating: 5,
      numReviews: 125,
      description: "Mitsubishi 39,000 Btu 19 Seer 4-Zone Mini Split Heat Pump System. Indirect or direct setting option Indirect or direct setting option. Option to set each vane separately Updated sleek, compact indoor unit design. Double vane air delivery for enhanced circulation. New multi-function hand held Wireless Remote Controlle. Natural flow setting that creates air movement like a natural breeze. Infrared human sensing technologies to measure location of human heat signatures i-see sensing floor temperature to deliver conditioned air to those areas by double vane airflow",
      features: "Remote Control",
      btu: 39000,
      areaCoverage: 139,
      energyEfficiency: 13,
      documents: [
        {
          url: "https://www.mitsubishi-electric.co.nz/materials/Aircon/Manuals/R410a/M-Series/MXZ/1_Operation/CapacityCharts_MXZ-2C52-6C120VA_OBH583A.pdf",
          type: "PDF",
          description: "User Manual for 39000 Btu 19 Seer 4-Zone Mini Split Heat Pump System",
        },
        {
          url: "https://www.mitsubishitechinfo.ca/sites/default/files/SB_MXZ-4C36NA2-U1_202102_0.pdf",
          type: "PDF",
          description: "Technical Specifications 39000 Btu 19 Seer 4-Zone Mini Split Heat Pump System",
        },
        {
          url: "https://manuals.plus/wp-content/uploads/2023/04/MITSUBISHI-ELECTRIC-MXZ-SM36NAM-Outdoor-Unit-Air-Conditioner-fig-16.jpg",
          type: "Image",
          description: "Installation Guide Image",
        },
      ],
    }
  ],
  sellers: [
    {
      name: 'LG',
      brand: "LG",
      rating: 4.5,
      info: "LG offers optimized Heating, Ventilation, and Air Conditioning for both commercial and residential solutions, ensuring fresh and crisp air for various environments.",
      link: "https://www.youtube.com/embed/df0y4MynElM?si=wXHBa1LmiWXyKsI3",
      numReviews: 15,
      isAdmin: false,
    },
    {
      name: 'Towalmark',
      brand: "Towalmark",
      info: "Experience superior comfort with our energy-efficient Split Air Conditioner, designed to deliver powerful cooling while minimizing electricity usage. Its quiet operation and sleek, modern design blend seamlessly into your living space, enhancing your home's ambiance. Offering flexible and customizable cooling options, advanced air filters for healthier air, and smart features like remote Wi-Fi control, our Split Air Conditioner is the perfect solution for maintaining an ideal indoor climate while reducing your environmental footprint.",
      link: "https://m.media-amazon.com/images/S/stores-image-uploads-na-prod/8/AmazonStores/ATVPDKIKX0DER/c5bbd56722a62cba36a71211b72d6ad4.w3000.h600._CR0%2C0%2C3000%2C600_SX1920_.jpg",
      rating: 4.0,
      numReviews: 13,
      isAdmin: false,
    },
    {
      name: 'Senville',
      brand: "Senville",
      info: "Senville.com is a leading retailer of mini split air conditioners and efficient heating and cooling products. Established in 2005, we've been helping to reduce energy consumption in home and businesses for over 10 years.",
      link: "https://www.youtube.com/embed/9EA8Lg5TWKE?si=9iJj50xZpOg87hr9",
      rating: 3.0,
      numReviews: 8,
      isAdmin: false,
    },
    {
      name: 'Daikin',
      brand: "Daikin",
      info: "The world's leading air conditioning manufacturer—Daikin. The source of the company's steady growth is its world-class air-conditioning technology developed in Japan. made possible high-quality air conditioners that responds to various user needs.",
      link: "https://www.youtube.com/embed/0JyUysKJRFQ?si=3BcBL3fdpA5oa92L",
      rating: 3.0,
      numReviews: 8,
      isAdmin: false,
    },
    {
      name: 'Samsung',
      brand: "Samsung",
      info: "Samsung provides the best air conditioner systems to fit your needs, whether you are seeking solutions for your home or for a business. WindFree™ technology creates a much gentler and milder air flow, evenly distributed through tens of thousands of micro holes, so people in the room feel almost no wind - just comfortable cool air",
      link: "https://www.youtube.com/embed/1dQ1MBSUHoQ?si=XgYwIiFsEHXc1Cl7&clip=UgkxU-wNgQmBp0v_YmQiAkAlIHFzL6GTFAIK&clipt=ENizARjwqAI",
      rating: 3.0,
      numReviews: 8,
      isAdmin: false,
    },
    {
      name: 'Mitsubishi Electric Corporation',
      brand: "Mitsubishi",
      info: "Mitsubishi Electric Corporation is a Japanese multinational electronics and electrical equipment manufacturing company headquartered in Tokyo, Japan. It was established in 1921 as a spin-off from the electrical machinery manufacturing business of Mitsubishi Shipbuilding (current Mitsubishi Heavy Industries) at the Kobe Shipyard. The products from MELCO include elevators and escalators, high-end home appliances, air conditioning, factory automation systems, train systems, electric motors, pumps, semiconductors, digital signage, and satellites.",
      link: "https://www.youtube.com/embed/DmPUadxWRBg?si=OecVhAlH7Nt20bAC",
      rating: 5.0,
      numReviews: 20,
      isAdmin: false,
    },
  ],
  contacts: [
    {
      fullName: "Jane Smith",
      mobilePhone: 9876543210,
      email: "jane_smith@example.com",
      country: "Canada",
      serviceType: "Air Conditioning Installation",
      equipmentAge: "1 year", // Corrected here
      subject: "Inquiry about installation",
      message: "I need a new air conditioner installed."
    },
    {
      fullName: "Jane Dow",
      mobilePhone: 9876544435,
      email: "jane-dow@example.com",
      country: "USA",
      serviceType: "Air Conditioning Service",
      equipmentAge: "3 years",
      subject: "Inquiry about service",
      message: "I need a new air conditioner serviced."
    }
  ],

  serviceProviders: [
    {
      name: 'Test One Company',
      email: 'test-company1@example.com',
      password: bcrypt.hashSync('12345', 8),
      typeOfProvider: 'designer',
      phone: '1234567890',
      company: 'test1',
      experience: 5,
      portfolio: 'portfolio1.link',
      isAdmin: false
    },
    {
      name: 'Test Two Company',
      email: 'test-company2@example.com',
      password: bcrypt.hashSync('test2company', 8),
      typeOfProvider: 'designer',
      phone: '1234567890',
      company: 'test2',
      experience: 7,
      portfolio: 'portfolio2.link',
      isAdmin: false
    },
    {
      name: 'Test Three Company',
      email: 'test-company3@example.com',
      password: bcrypt.hashSync('test3company', 8),
      typeOfProvider: 'Architect',
      phone: '1234567890',
      company: 'test3',
      experience: 9,
      portfolio: 'portfolio3.link',
      isAdmin: false
    },
  ],
  projects: [
    {
      name: "Residential House Design",
      client: "John Doe",
      dueDate: "2024-12-23",
      status: "In Progress",
      serviceProvider: "test-company1@example.com",
      hoursWorked: 20,
    },
    {
      name: "Loft Renovation",
      client: "Loft&Hubs Corp",
      dueDate: "2024-12-13",
      status: "Completed",
      serviceProvider: "test-company1@example.com",
      hoursWorked: 123,
    },
    {
      name: "Loft Renovation",
      client: "Loft&Hubs Corp",
      dueDate: "2024-12-13",
      status: "Completed",
      serviceProvider: "test-company1@example.com",
      hoursWorked: 123,
    },
    {
      name: "Office Interior Renovation",
      client: "ABC Corp",
      dueDate: "2024-12-10",
      status: "Completed",
      serviceProvider: "test-company2@example.com",
      hoursWorked: 40,
    },
    {
      name: "Appartments Design",
      client: "Michaella Donowan",
      dueDate: "2024-12-23",
      status: "In Progress",
      serviceProvider: "test-company2@example.com",
      hoursWorked: 53,
    },
    {
      name: "Construction Design",
      client: "Viki Crage",
      dueDate: "2024-11-15",
      status: "In Progress",
      serviceProvider: "test-company3@example.com",
      hoursWorked: 30,
    },
    {
      name: "Ventilation System Architecting",
      client: "Venty Corp",
      dueDate: "2024-11-26",
      status: "Completed",
      serviceProvider: "test-company3@example.com",
      hoursWorked: 78,
    },
  ],
  messages: [
    {
      client: "John Doe",
      text: "Can we update the room layout?",
      date: "2024-12-26",
      serviceProvider: "",
      projectName: "Residential House Design"
    },
    {
      client: "ABC Corp",
      text: "Can we upgrade the office layout?",
      date: "2024-10-26",
      serviceProvider: "",
      projectName: "Office Interior Renovation"
    },
    {
      client: "Viki Crage",
      text: "Can we upgrade the construction layout?",
      date: "2024-11-25",
      serviceProvider: "",
      projectName: "Construction Design",
    },

    {
      client: "Loft&Hubs Corp",
      text: "We obtained the last transh and last milestone",
      date: "2024-11-05",
      serviceProvider: "",
      projectName: "Loft Renovation",

    },
    {
      client: "Michaella Donowan",
      text: "When can we start nogotiation regarding the first draft be ready?",
      date: "2024-12-30",
      serviceProvider: "",
      projectName: "Appartments Design"
    },

    {
      client: "Venty Corp",
      text: "When will we get the first transh for the first draft and previous milestone?",
      date: "2024-09-15",
      serviceProvider: "",
      projectName: "Ventilation System Architecting"
    },

  ],
  earnings: [
    {

      amount: 500,
      date: '2024-12-20',
      hoursWorked: 20,
      status: 'Pending',
    },
    {

      amount: 1500,
      date: '2024-11-29',
      hoursWorked: 40,
      status: 'Paid',
    },
    {

      amount: 850,
      date: '2024-12-24',
      hoursWorked: 30,
      status: 'Pending',
    },
    {

      amount: 2345,
      date: '2024-12-04',
      hoursWorked: 123,
      status: 'Paid',
    },
    {

      amount: 699,
      date: '2024-12-20',
      hoursWorked: 53,
      status: 'Pending',
    },
    {

      amount: 2500,
      date: '2024-12-13',
      hoursWorked: 78,
      status: 'Paid',
    },
  ],
  notifications: [
    {
      title: 'High-Earning Service Provider',
      message: 'Test Three Company has exceeded $2500 earnings!',
      type: 'info',
      recipientType: 'admin',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: 'To implement marketing company for new users.',
      message: 'The marketing company is devoted for new users. To make an asquantence with new service and new products.',
      type: 'urgent',
      recipientType: 'admin',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: 'Pending Orders Alert',
      message: 'There are more than 2 pending orders. Immediate action is required.',
      type: 'info',
      recipientType: 'admin',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: 'Pending Orders Alert',
      message: 'There are more than 2 pending orders. Immediate action is required.',
      type: 'info',
      recipientType: 'admin',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: 'Discount Offer',
      message: 'Check out the latest discount offers!',
      type: 'discount',
      recipientType: 'user',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: 'Service Request Assigned',
      message: 'You have been assigned a new service request for an air conditioner installation. Please review the details and respond promptly.',
      type: 'urgent',
      recipientType: 'serviceProvider',
      isRead: false,
      createdAt: new Date(),
    },
    {
      title: "Get A Quote",
      message: "Your Dream Deal Starts Here – Get a Quote Now!",
      type: "quote",
      recipientType: "user",
      isRead: false,
      createdAt: new Date(),
    },

  ],


  blogs: [
    {
      title: "Elevate your comfort wherever you are:",
      slug: "elevate-your-comfort",
      content: "<h1>Understanding Indoor Air Quality</h1><p>Indoor air quality is an important factor to consider when evaluating the health and comfort of building residents. Indoor air quality can also be influenced by different factors such as:</p><h2>Pollutants</h2><p>Dust, pollen, pet hair, mould spores, and VOCs (volatile organic compounds) released from home products and furniture are some common indoor pollutants.</p><h2>Ventilation</h2><p>Inadequate ventilation leads to the accumulation of indoor pollutants and moisture, which creates an environment for mould and bacteria growth.</p><h2>Outdoor Air Quality</h2><p>Pollutants from outside, such as car exhausts or industrial emissions, may penetrate rooms, making them even worse than before.</p><h2>Health Risks Of Poor Indoor Air Quality</h2><p>Exposure to poor indoor air quality can have various short-term and long-term health effects. These effects can range from mild to severe, depending on the level of exposure, the types of pollutants present, and the individual’s sensitivity.</p><h3>Respiratory Issues</h3><p>Respiratory discomfort is one of the most immediate and prevalent consequences of poor indoor air quality. Pollutants, including dust mites, pet dander, and mould spores, can irritate the respiratory system, resulting in:</p><ul><li><strong>Coughing and sneezing</strong> The body uses coughs and sneezes as methods to eliminate airborne irritants.</li><li><strong>Frequent asthmatic episodes</strong> – People who have asthma might face more frequent and severe episodes because of their contact with indoor allergens and pollutants.</li><li><strong>Chronic bronchitis</strong> Chronic bronchitis, characterised by long-standing cough and excessive mucus production, may result from persistent exposure to poor indoor air quality.</li></ul><h3>Allergic Reactions</h3><p>Indoor air pollutants can act as allergens, triggering allergic reactions in many people. Common symptoms of indoor allergies include:</p><ul><li><strong>Runny or stuffy nose</strong> Allergens like dust mites and pollen can cause nasal congestion and runny nose.</li><li><strong>Itchy eyes and skin</strong> Contact with certain indoor pollutants can lead to itchy, watery eyes and skin irritation.</li><li><strong>Throat irritation</strong> Allergens and irritants can cause a sore or scratchy throat.</li></ul><h3>Headaches And Fatigue</h3><p>Poor indoor air quality may result in headaches, dizziness, and fatigue. Most of the time, this is attributed to exposure to VOCs, carbon monoxide, or other chemicals present in some household items and furniture. Later, these symptoms may become worse due to inadequate ventilation that allows pollutants to accumulate.</p><h3>Long-Term Health Effects</h3><p>Chronic hazards of poor indoor air quality can lead to severe long-term health issues, including:</p><ul><li><strong>Prolonged lasting respiratory diseases</strong> Constant exposure to indoor air pollutants can make one’s risk for chronic obstructive pulmonary disease (COPD).</li><li><strong>Cardiovascular complications</strong>  Some researchers have established a connection between bad indoor air quality and increased chances of suffering from heart disease and hypertension.</li><li><strong>Neurological effects</strong> – Certain indoor pollutants, such as lead and formaldehyde, can affect brain function over time, leading to neurodegenerative diseases.</li></ul><h2>How Your AC System Can Help Improve Indoor Air Quality</h2><p>When properly cared for, an AC system can be among the most potent devices for improving indoor air quality and reducing health dangers from polluted air. Here’s how:</p><h3>Pollutants’ Filtration</h3><p>The latest AC units come with air filters that trap dust, pollen, pet dander, and other airborne particles. These filters must be changed or cleaned regularly to keep capturing pollutants effectively. HEPA filters are very efficient in removing the smallest particles in the air, thus improving general air quality.</p><h3>Humidity Control</h3><p>Humidity levels play an important role in indoor air quality. When there is too much humidity, dust mites thrive, triggering respiratory problems or allergies. AC systems help control indoor humidity by draining excessive moisture from the air, thus preventing mould growth and decreasing the dust mite population.</p><h3>Ventilation And Circulation Of Air</h3><p>The circulation of fresh outdoor air into the house and the expulsion of stale indoor air through AC systems promote better circulation of indoor air. This process dilutes indoor pollutant concentrations, contributing to an improvement in the overall quality of indoor air. Proper ventilation is necessary in rooms with high levels of indoor pollutants, such as kitchens and bathrooms.</p><h3>Reducing VOCs And Odours</h3><p>Indoor air conditioners are known to reduce the concentration of these harmful fumes as they promote air circulation inside rooms. They have activated carbon filters that are very efficient in removing these impurities, thus transforming unhealthy and uncomfortable environments into clean and liveable spaces.</p><h2>Tips For Maintaining Your AC System For Better Air Quality</h2><h3>Regularly Change Air Filters</h3><p>Depending on how often you use it or such other factors, you should replace or clean your air filters every 1-3 months. This step ensures proper filtration of pollutants by your AC system.</p><h3>Contact Experts</h3><p>You should get an expert to check and service this equipment at least annually. The procedure helps identify everything that can destroy or affect your room’s sanity by affecting its freshening process.</p><h3>Clean The Ducts</h3><p>A build-up of dust and dirt within these ducts reduces the efficiency of your appliance and disperses impurities into the atmosphere. You can avoid this by cleaning the duct regularly.</p><h3>Dehumidification</h3><p>In humid areas, consider using a dehumidifier together with your AC system to maintain optimal humidity levels.</p><h3>Ventilation</h3><p>Make sure your home has good ventilation so that the perfect fresh air can find its way in while the stale one goes out. This can be done by using exhaust fans, leaving windows open, or installing proper ventilators.</p>",
      shortDescription: "Discover the perfect fit for your needs.",
      image: "https://www.mitsubishielectric.com.au/wp-content/uploads/2021/11/Plasma-Quad-Connect_MSZ-AP-Loungeroom-1920x1080px-1024x576.png",


    },
    {
      title: "Preventative Measures To AC.",
      slug: "preventative-measures-ac",
      content: "<h2>7 Preventative Measures To Minimise Air Conditioning Repair Needs</h2><h3>1. Regular Maintenance Checks</h3><p>Schedule regular maintenance checks with a professional to ensure your air conditioning system operates efficiently. During these checks, technicians inspect all components, clean necessary parts, and identify potential issues before they escalate into serious problems.</p><p>Regular maintenance can extend the lifespan of your unit and improve its performance. It is recommended to have maintenance checks at least once a year, ideally before the start of the cooling season.</p><p>By addressing minor issues early, you prevent them from developing into costly repairs, ensuring your system remains reliable and efficient throughout the year.</p><h3>2. Clean Or Replace Filters</h3><p>Clean or replace air filters every one to three months to maintain proper airflow and system efficiency. Dirty filters restrict airflow and force the air conditioning system to work harder, which can lead to increased energy consumption and potential breakdowns.</p> <p>Changing filters ensures clean air circulation, improves indoor air quality, and reduces the strain on your system. For homes with pets or in high-pollution areas, more frequent filter changes may be necessary.</p><p>A clean filter not only helps the system run more efficiently but also prolongs its lifespan, saving you money on energy bills and future repairs.</p><h3>3. Inspect And Clean Coils</h3><p>Ensure that both the evaporator and condenser coils are clean to maintain the efficiency of your air conditioning system. Over time, dirt and debris can accumulate on these coils, reducing their ability to absorb and release heat effectively.</p><p>Dirty coils cause the system to work harder, which leads to increased energy consumption and potential component failures. Regular cleaning, typically during annual maintenance checks, helps maintain optimal performance and energy efficiency.</p><p>Furthermore, clean coils ensure better heat exchange, lower energy bills, and a longer lifespan for your system. Maintaining them is crucial for preventing unnecessary wear and tear on your air conditioning unit.</p><h3>4. Check Thermostat Settings</h3><p>Verify that your thermostat settings are accurate and suited to your comfort needs. Incorrect settings can cause the air conditioning system to cycle on and off frequently, leading to increased wear and tear and higher energy bills.</p> <p>Consider upgrading to a programmable thermostat for better control and energy efficiency. A programmable thermostat allows you to set different temperatures for various times of the day. This ensures optimal comfort while reducing unnecessary usage.</p><h3>5. Clear Debris From Around The Unit</h3><p>Keep the area around your outdoor unit free from debris such as leaves, grass, and other obstructions. These items can impede airflow, causing the system to work harder and potentially overheat.</p><p>Maintaining a clear space of at least two feet around the unit ensures proper airflow and efficient operation. Check the area on a regular basis and remove any debris that may accumulate. Proper airflow is essential for the system to release heat effectively, which is critical for maintaining optimal performance.</p><h3>6. Ensure Proper Refrigerant Levels</h3><p>Have a professional check the refrigerant levels in your air conditioning system regularly. Low refrigerant levels can cause the system to overheat and fail.</p><p>Proper refrigerant levels are also crucial for preventing damage to the compressor. If your system is low on refrigerant, it may indicate a leak that needs to be addressed immediately.</p><p>Periodic checks ensure that your system has the correct amount of refrigerant, which is vital for maintaining cooling efficiency and preventing strain on the unit.</p><h3>7. Check And Tighten Electrical Connections</h3><p>Over time, electrical connections within your air conditioning system can become loose. This may lead to potential system failures and safety hazards. Regularly check and tighten these connections to ensure reliable operation.</p><p>During routine maintenance checks, professionals will examine these connections to ensure they are secure and functioning correctly. Keeping electrical connections tight prevents unnecessary wear on the system and helps avoid costly repairs.</p><p>This simple yet crucial step enhances the overall reliability and safety of your air conditioning unit.</p></section><section ><h2>JP Air Conditioning – For Expert Installation, Servicing, Repairs</h2><p>At JP Air Conditioning, we pride ourselves on being London’s premier air conditioning experts with over 15 years’ experience in the field. Our comprehensive services cover all aspects of air conditioning, from installation and servicing to repairs, ensuring your building remains comfortable year-round.</p><p>Rest assured, our skilled engineers are dedicated to meeting your needs, whether through regular servicing or one-off maintenance visits. We work around your schedule, offering flexible service times to minimise disruption to your home or business operations.</p><p>Finally, at the end of each servicing, we provide a detailed, written report, signed by our engineer, outlining any additional repairs that might be necessary.</p>",
      shortDescription: "Preventative Measures To Minimise Air Conditioning Repair Needs.",
      image: "https://assets.fixr.com/cost_guides/annual-air-conditioner-maintenance/annual-air-conditioner-maintenance-5ed7b071349f8.png",

    },
    {
      title: "What Temperature Should You Set The Air Conditioner in Summer?",
      slug: "what-temperature-of-ac",
      content: "<h2>What is the Ideal AC Temperature for Summer?</h2><p> Well, the prime thing to bear in your mind is that there is a perfect temperature at which you can set your thermostat during the summer months. However, you cannot keep it at the same temperature during the day and night.</p><p>The temperature has to vary. If we talk about the temperature during the day, the general rule is to keep a difference of -6.6 degrees Celsius between the indoor and outdoor temperatures. This should be done to ensure that if you have to go outdoors, the temperature difference is easily bearable by the body.</p> <h3>Best Temperature for Day!</h3><p>The best temperature to run your AC during the day is 27 to 29 degrees Celsius. If you run your AC between or at these temperatures for eight hours, you can easily save 5-15% on the overall cooling cost.</p><p>Though this is an ideal setting for the AC temperature, the required AC temperature can vary a little based on various factors. These factors are the location of your house, the insulation of your house, the time of the day, etc. In areas like London, the ideal AC temperature is between 21 to 25 degrees Celsius.</p><h3>Best Temperature for Night!</h3> <p>When it comes to nighttime, the temperature outdoors drops during the night, which is why you need to lower the AC temperature. The ideal temperature to set your AC to at night is 15 and 19 degrees Celsius. It is better to use sleep mode on your AC as it will turn OFF the AC after some time, saving you money.</p><h3>Can I Automate the Temperature Settings of the Air Conditioner?</h3><p>If you are a working-class person, it can be a bit inconvenient to turn the AC ON and OFF repeatedly. Moreover, keeping track of the temperature and adjusting it after coming from work can be irritating. This is where the need for automation or a programmable thermostat comes into the picture.</p><p>A programmable thermostat is an excellent device that can help keep your home at the right temperature while you are away. For example, if you are out, it will keep the temperature higher and reduce it to your set value when you are ready to come home. The device can be a great way to save more power.</p><h3>Essential Tips to Obtain the Best Out of Your AC in Summers!</h3><p> Ok, now we know what the ideal temperature for your AC for this summer is. But, it is not going to be enough. You will reap no benefits from setting the AC at 25 or 26 degrees Celsius if you haven’t taken care of the other factors.</p><p>So, here are some tips that you need to implement to get the best air conditioning installation this summer.</p><ul><li> <strong>Use a ceiling fan:</strong> Using an AC is not going to be enough if you want to cool in multiple rooms. Cool air is heavy, which is why it accumulates wherever it is released. Therefore, it is necessary to have a ceiling fan that circulates the air. This will significantly affect your power bill.</li> <li><strong>Keep the doors and windows closed:</strong> Your AC will not deliver performance if you leave the doors & windows open. You see, the AC captures the hot air in the room, cools it, and releases it back into the house. Hence, if the hot air outside is coming inside, the overall cooling effect will be hampered. </li><li><strong>Keep a check on the air filters:</strong> No matter what temperature your AC is set to, if the filters used in the AC are not clean, your AC will require more power to suck the air in and deliver cold air out. Hence, if your AC has removable filters, take them out and clean them on a regular basis.</li> </ul><p>Keep all these things in mind, and you will never face high power bills due to your AC, at least.</p>",
      shortDescription: "What is the Ideal AC Temperature for Summer?",
      image: "https://blog.waltonbd.com/wp-content/uploads/2022/04/5-What-Temperature-Should-I-set-my-AC-during-summer.jpg",
    },
    {
      title: " Problems With Air Conditioner And Tips To Prevent Them.",
      slug: "3-common-air-conditioning-problems",
      content: " <h2>What is the Ideal AC Temperature for Summer?</h2> <p> The prime thing to bear in your mind is that there is a perfect temperature at which you can set  thermostat during the summer months. However, you cannot keep it at the same temperature during the day and night.</p> <p>The temperature has to vary. If we talk about the temperature during the day, the general rule is to keep a difference of -6.6 degrees Celsius between the indoor and outdoor temperatures. This should be done to ensure that if you have to go outdoors, the temperature difference is easily bearable by the body.</p><h3>Best Temperature for Day!</h3><p>The best temperature to run your AC during the day is 27 to 29 degrees Celsius. If you run your AC between or at these temperatures for eight hours, you can easily save 5-15% on the overall cooling cost. </p><p>Though this is an ideal setting for the AC temperature, the required AC temperature can vary a little based on various factors. These factors are the location of your house, the insulation of your house, the time of the day, etc. In areas like London, the ideal AC temperature is between 21 to 25 degrees Celsius.</p><h3>Best Temperature for Night!</h3><p>When it comes to nighttime, the temperature outdoors drops during the night, which is why you need to lower the AC temperature. The ideal temperature to set your AC to at night is 15 and 19 degrees Celsius. It is better to use sleep mode on your AC as it will turn OFF the AC after some time, saving you money.</p><h3>Can I Automate the Temperature Settings of the Air Conditioner?</h3><p>If you are a working-class person, it can be a bit inconvenient to turn the AC ON and OFF repeatedly. Moreover, keeping track of the temperature and adjusting it after coming from work can be irritating. This is where the need for automation or a programmable thermostat comes into the picture.</p><p>A programmable thermostat is an excellent device that can help keep your home at the right temperature while you are away. For example, if you are out, it will keep the temperature higher and reduce it to your set value when you are ready to come home. The device can be a great way to save more power.</p><h3>Essential Tips to Obtain the Best Out of Your AC in Summers!</h3><p>Ok, now we know what the ideal temperature for your AC for this summer is. But, it is not going to be enough. You will reap no benefits from setting the AC at 25 or 26 degrees Celsius if you haven’t taken care of the other factors.</p><p>So, here are some tips that you need to implement to get the best air conditioning installation this summer.</p><ul><li><strong>Use a ceiling fan:</strong> Using an AC is not going to be enough if you want to cool in multiple rooms. Cool air is heavy, which is why it accumulates wherever it is released. Therefore, it is necessary to have a ceiling fan that circulates the air. This will significantly affect your power bill.</li><li><strong>Keep the doors and windows closed:</strong> Your AC will not deliver performance if you leave the doors & windows open. You see, the AC captures the hot air in the room, cools it, and releases it back into the house. Hence, if the hot air outside is coming inside, the overall cooling effect will be hampered.</li><li><strong>Keep a check on the air filters:</strong> No matter what temperature your AC is set to, if the filters used in the AC are not clean, your AC will require more power to suck the air in and deliver cold air out. Hence, if your AC has removable filters, take them out and clean them on a regular basis.</li></ul><p>Keep all these things in mind, and you will never face high power bills due to your AC, at least.</p><h2>Common Problems with Air Conditioners</h2><p>With the summer months comes the summer heat. On a sweltering day with temperatures reaching triple digits and 100 percent humidity, the last thing anyone wants to deal with is a broken air conditioner. Here are some common problems many encounter with their air conditioners and tips to prevent them from happening to you. </p><h3>Just Plain Dirty</h3><p>One of the most common problems air conditioners face stems from the fact they are just plain dirty. Dirt can cause some serious issues when they build up in the air filter and on the coils. When this happens, the airflow from the machine into the room will decrease, and the unit will literally freeze, shutting down.</p><p>This problem can best be prevented by basic maintenance with regular cleaning of the filter and coils. Keeping the buildup of dirt and dust to a minimum will ensure your air conditioner can do its best in the hot months ahead.</p><h3>Leaking Refrigerant</h3> <p> Refrigerant is the lifeblood in your air conditioner that helps the hot and wet air around you become that nice cool and dry air you enjoy. A common problem is a leak in the tubing of the air conditioner that holds the refrigerant.</p><p>When the level of refrigerant is at the exact level recommended by manufacturers, the machine will work at its best. When there is more or less refrigerant than that level, the machine will not work at its best. If you add more refrigerant to your air conditioner with no improvement to the quality of air that comes out, you might have a leak. The best way to fix this problem is to call a professional who will be able to repair the leak and get your HVAC system back to the right levels again. With refrigerant distribution strictly controlled by our government, you cannot continue to re-charge a leaking system.</p><h3>Electric Control Failure</h3><p>If you tend to turn your air conditioner on and off frequently, a problem can develop with the electric controls. When the weather is hot and humid, you should leave the system on and just raise the temperature a maximum of 5 degrees when not home. If you think the unit is not keeping the temperature you wish, an electrical problem as simple as your thermostat may be the culprit.</p>",
      shortDescription: "3 Common Air Conditioning Problems And Tips To Prevent Them.",
      image: "https://metropha.com/wp-content/uploads/2018/03/How-to-Deal-with-Air-Conditioner-Issues-Air-Conditioner-Repair-in-Chattanooga-TN.jpg",
    },
    {
      title: " Everything You Should Know About Air Conditioning.",
      slug: "everything-you-should-know-about-air-conditioning",
      content: " <h2>Types of Air Conditioners.</h2><article><p>Central Air Conditioner: A central air conditioner is usually the   best choice if you have a large home or want to cool in more than one room. A central air conditioner circulates air throughout your home using a system of air ducts. </p><p> Room Air Conditioners: Room air conditioners are perfect for cooling   small spaces, like a single room or an apartment. Room air  conditioners usually sit in a window or can be mounted on a wall.</p><p> Ductless Mini-Split Air Conditioner: A ductless mini-split air conditioner is similar to a room air conditioner, but it doesn't need an air duct. Instead, a small air conditioner unit sits inside your home, and a small compressor sits outside.           </p>   <p>            Portable Air Conditioner: A portable air conditioner is an excellent  option if you need to cool a small space and you don't want to  install a window air conditioner. Portable air conditioners can be             moved from room to room, and they usually sit on the floor.</p><p>   A window air conditioner is a single unit with all of its components             enclosed inside. It ejects heat out of its outdoor side and blows             cool air into the room on the indoor side. As the name suggests, it             is installed in a window or by making a hole in the wall. Such air  conditioners have a filter that slides out so that it can be cleaned  regularly for full AC efficiency. These air conditioners have             controls on the unit & may also come with a remote.  </p>   <p>     Floor-mounted air conditioners are designed for convenience if you  prefer a mini-split but lack the required space for a wall mounted             unit. The indoor unit of floor-mounted AC rests on the floor, and             the outer unit can be installed without major site preparation or             any ductwork. This arrangement is also ideal for spaces with tilted   walls, such as attics, or building constructed with fragile             materials such as glass.           </p>   <p>            Smart air conditioners are a type of mini-split, window, or portable             air conditioner that are IoT enabled. These ACs are connected to             Wi-Fi and come with a native app providing global control through a             smartphone. Depending on the manufacturer, these air conditioners             come with numerous functionalities. Some of these include weekly             scheduling, geofencing, comfy mode, temperature range control, and             numerous other features. Utilizing these, you can achieve great             comfort coupled with energy savings.           </p>   <p>            Geothermal heating & cooling is considered a relatively new method,             it works by utilizing the insulating properties of the earth. Since             the temperatures under 4 to 6 feet of land remain consistent all             year regardless of the weather, geothermal technology takes             advantage of this to heat & cool your home more efficiently. This   system has piping that consists of a loop that circulates water  between your home, a heat pump & the ground. They require intensive             work to set up underground. </p>   <p>  Hybrid / Dual Fuel Air Conditioner system is one that combines a gas  furnace with an electric air-source heat pump to deliver a             cost-effective & efficient performance in terms of heating &  cooling. Depending on the temperature outdoors, the system   automatically switches between burning fossil fuels and the usage of             electricity. You program the temperature at which the system             switches from heat pump to furnace, or you can make the manual             switch too.           </p>   <p>  Evaporative coolers are sometimes categorized as air conditioning  alternatives, even though technically, they are not air conditioners             and differ in both mechanism and structure. This inclusion in the             list stems from their ability to effectively cool indoor spaces.  Unlike conventional AC systems with ducts and refrigeration cycles, evaporative coolers operate by drawing in warm air through water-saturated pads or media.</p></article>",
      shortDescription: "Types of Air Conditioners.",
      image: "https://accessglobal.media.clients.ellingtoncms.com/uploads/froala_editor/images/1728398396923.png",
    },
    {
      title: "How to Choose The Best Air Conditioner For Your Needs.",
      slug: "how-to-choose-the-best-ac",
      content: "<article><h2>Factors to Consider Before Buying an Air Conditioner </h2>  <p >When choosing an air conditioner, there are many factors you need to  consider making the best decision for your home. The first thing you  need to do is figure out the room's square footage or rooms you want to cool. Once you know that, you can start looking at air conditioners and their cooling capacity.  </p>  <p > The next thing you need to consider is the air conditioner's features.  Some air conditioners come with features like timers and remote  controls. These can be very helpful if you want to be able to cool  your home before you get home from work or turn off the air  conditioner when you leave for vacation. Finally, you need to think  about your budget. Air conditioners can range from a few hundred  dollars to several thousand dollars. Therefore, it's crucial to find  an air conditioner that fits your needs and budget. Installing an air  conditioner can be a great way to improve the comfort of your home. But, it's essential to do your research and choose the right air  conditioner for your home. By considering the size of the room, the  features you want, and your budget, you can find an air conditioner  that will keep you cool all summer long.   </p></article>",
      shortDescription: "Factors you need to consider making the best decision.",
      image: "https://www.sandersandjohnson.com/wp-content/uploads/house_cut.png",
    },
    {
      title: "Where is the best location for your split system air conditioner installation.",
      slug: "ac-installation",
      content: "<article><h2>The Importance of Proper Installation for Your Split System Air Conditioner</h2> <p >The placement and installation of your split system air conditioner can significantly influence its efficiency and performance. If installed in an unsuitable location, it may struggle to adequately heat or cool your space. </p> <p >To ensure you remain comfortable during the summer and warm in the winter, we’ve addressed the crucial question: where is the best location for your split system air conditioner? </p> <p>Optimal Installation Locations for Your Split System Air Conditioner. When selecting a site for your split system air conditioner, keep these straightforward guidelines in mind: Install Where It’s Most Needed Consider where you spend the most time at home. For many, this is the lounge area, making a central position in this room an excellent choice for installation. If you work from home or have trouble sleeping on warm nights, your home office or bedroom might also be a suitable option. </p> <p >Choose a Central Spot in the Room It’s generally beneficial to install your split system air conditioner centrally within the room for effective heating and cooling of the entire space. Positioning it above where you typically sit, like your couch in the lounge or your office chair, can enhance its efficiency. </p> <p > Install High on the Wall (2+ Meters) Since hot air rises and cool air sinks, installing your air conditioner at a height of over 2 meters can significantly improve air distribution throughout the room. </p> <p > Ensure Adequate Clearance of 15 cm Around the Unit Proper airflow around the air conditioner is essential, so make sure there’s at least 15 cm of clearance on each side. </p></article> <article><h3>Whole House vs. Room Heating & Cooling</h3> <p >Consider whether you intend to heat just one room or your entire home when deciding where to install your split system air conditioner. If heating a single room, follow the guidelines to install it where it’s most needed. However, opt for a central location within the property for whole-home heating. </p> <p> Ensure that you select a split system air conditioner with sufficient power to heat and cool your entire home effectively. Refer to our guide on choosing the right size air conditioner for more information. </p> <p> Installing a Split System Air Conditioner in Your Bedroom If you're placing a split air conditioner in your bedroom, avoid positioning it too close to your bed, as this could disrupt your sleep by directing cold or hot air at you. Alternatively, if it's not centrally located its efficiency may be compromised. </p> <p> To resolve this issue, consider purchasing a unit with adjustable louvers, such as those from Carrier’s range of split system air conditioners. This allows you to install it centrally—above, to the side, or at the foot of your bed—and adjust the airflow direction so that it doesn’t blow directly onto you. </p> </article><article><h3> Positioning the Outdoor Unit of Your Split System Air Conditioner. </h3> <h3> When selecting a location for your split AC’s outdoor unit, consider the following: </h3> <p > Position it away from direct sunlight whenever possible; the southeast or south side of your home, shielded from the afternoon sun, is often ideal. Ensure it is located in an open area for proper airflow around the unit. The outdoor unit should be easily accessible for maintenance and repairs. If feasible, install it on a flat, sturdy surface to minimize vibration. Place it as close to the indoor unit as possible to maximize efficiency. Deciding where to install your split AC unit should be your first consideration when purchasing a new system. Taking the time to evaluate the best location and seeking professional installation help will enhance your air conditioner's performance and reduce operational costs. </p> </article>",
      shortDescription: "Air conditioner installation.",
      image: "https://grovehvac.com/wp-content/uploads/2021/07/Grove_Tune-Up-scaled.jpeg",
    },
    {
      title: "What Is a BTU and Why Does It Make Sence?",
      slug: "ac-btu",
      content: "<article><h2>Air Conditioning and BTU.</h2><p > The British Thermal Unit, or BTU, is an energy unit. It is approximately the energy needed to heat one pound of water at 1 degree Fahrenheit. 1 BTU = 1,055 joules, 252 calories, 0.293 watt-hours, or the energy released by burning one match. 1 watt is approximately 3.412 BTU per hour. </p> <p > BTU is often used as a point of reference for comparing different fuels. Even though they're physical commodities and are quantified accordingly, such as by volume or barrels, they can be converted to BTUs depending on the energy or heat content inherent in each quantity. BTU as a unit of measurement is more useful than physical quantity because of fuel's intrinsic value as an energy source. This allows many different commodities with intrinsic energy properties, such as natural gas and oil, to be compared. </p> <p> BTU can also be used pragmatically as a point of reference for heat that an appliance generates. The higher the BTU rating of an appliance, the greater the heating capacity. As for air conditioning in homes, even though ACs are meant to cool homes, BTUs on the technical label refer to how much heat the air conditioner can remove from their respective surrounding air. </p> <p > Air conditioners come in a range of sizes, designed to cool different volumes of air. The rating of an air conditioner is measured in BTUs, and you need to know how many BTUs will be required to cool your room. Above is a chart that will tell you the BTUs required for different sizes of rooms. Simply work out how big your room is (measure the length of your room and multiply it by the width) and then you will know roughly how many BTUs your air conditioner requires. Air conditioners come in a range of sizes, designed to cool different volumes of air. The rating of an air conditioner is measured in BTUs, and you need to know how many BTUs will be required to cool your room. Above is a chart that will tell you the BTUs required for different sizes of rooms. Simply work out how big your room is (measure the length of your room and multiply it by the width) and then you will know roughly how many BTUs your air conditioner requires. </p> </article>",
      shortDescription: "Air conditioning and BTU",
      image: "https://www.keroclima.pt/WebRoot/ce_pt/Shops/960844166/MediaGallery/Logo_Marcas/BTU_3.png",

    },
    {
      title: "What is Air Conditioning, and How Does it Work?",
      slug: "ac-how-it-works",
      content: "<article><h2>Air Conditioning.</h2><p > Air conditioning is a system that helps to regulate the temperature and humidity in a space. Air conditioners work by circulating air in a room and removing warm air and moisture. This exchange process also helps filter out pollutants, dust, and other allergens from the air.</p><p>   Air conditioners come in many different shapes and sizes, but the most common type is the central air conditioner. Central air conditioners are usually located in a home's basement or crawl space and use ductwork to distribute cool air. There are many benefits to air conditioning, but some of the most notable include improved air quality. </p> <h3>Air conditioning good and bad sides </h3> <p>   Installing air conditioning in your property has both good and bad sides. The good side is that air conditioning can improve air quality by circulating and filtering air. This can be beneficial for people with allergies or respiratory problems.  </p> <p>   Air condition can also help keep your home cool during hot weather, which can be a relief from the heat. The bad side of air condition is that it can increase your energy bills. Air condition also produces noise, which can be annoying for some people. If you're considering air conditioning for your home, weigh the pros and cons to decide if it's right for you </p> </article>",
      shortDescription: "Air conditioning and how it works.",
      image: "https://holtzople.com/wp-content/uploads/2015/04/how-air-conditioning-systems-work.jpg",

    },
  ]
}

export default data;